### PR TITLE
Prepare Release 2.2.0

### PR DESCRIPTION
**Pull request by BONNe**

### CODE REVIEW

**Comment by andris155** [comment]
https://github.com/BentoBoxWorld/MagicCobblestoneGenerator/issues/81

**Comment by BONNe** [comment]
@tastybento and @Poslovitch I mostly want one of you to check locales for obvious mistakes :)

**Comment by tastybento** [comment]
I edited it and put the PR here: https://github.com/BentoBoxWorld/MagicCobblestoneGenerator/pull/82

**Review by Poslovitch — APPROVED** [review]
Code looks good to me and locales too.
Before merging, could you please make sure to replaces the tabs with spaces? Or at least one of these two? I see that some files are using both.

**Review by tastybento — APPROVED** [review]
LGTM

**Comment by BONNe** [comment]
I need to solve one issue, and will commit changes... 
The release will be tomorrow :(

**Pull request merged**
